#!/bin/bash
# archivo argumentos
# Ejemplo 2: Paso de argumentos en la línea de comandos
# Modo de uso: ./argumentos [nombre] [apellido]
echo "Bienvenido a $0"
echo "Su nombre es $1"
echo "Su apellido es $2"
echo "Todas las variables sumadas: $*"
